[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "surprise_travel"
version = "0.1.0"
description = "surprise-travel using crewAI"
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.152.0",
    "crewai-tools>=0.58.0",
]
